// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function App(Props) {
  return React.createElement("div", undefined, "Silence is golden");
}

var make = App;

exports.make = make;
/* react Not a pure module */
