// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Gretting = require("./Gretting.bs.js");

function App(Props) {
  console.log(Gretting.make(1, 2));
  return React.createElement("div", undefined, "Silence is golden");
}

var make = App;

exports.make = make;
/* react Not a pure module */
